### ISSUE TITLE
May I ask when you can upload it? I'm really looking forward to it

### ISSUE THREAD

**Issue by xwpwx** [kang-1-2-3/CoFiI2P#1]

**Comment by martin-liao** [comment]
Thanks for your interest. We are still awaiting the first-round review comments. We will upload the code and pre-trained models as soon as the review comments are received.

**Comment by INDEX108** [comment]
May I ask if there is a specific estimated time for open source? I'm also looking forward to it. @martin-liao

**Comment by martin-liao** [comment]
Thanks for your interest.  We are migrating the repository to [WHU-USI3DV/CoFiI2P](https://github.com/WHU-USI3DV/CoFiI2P) and making it open-source within two weeks (no later than 5.31). Please be patient.

**Comment by martin-liao** [comment]
We have released the code at [CoFiI2P](https://github.com/WHU-USI3DV/CoFiI2P).

**Comment by martin-liao** [comment]
Since the problem has been resolved, I will close the issue.
